exports.permit =

  {
   "chosenPermitID":"SR-2015-18",
   "baselineReportRequired":"No",
   "permitCode":"SR2015 No 18",
   "firePlanNeeded":"Yes",
   "friendlyWeight":"Less than 25,000 tonnes a year of waste metal and less than 5,000 tonnes a year of waste motor vehicles",
   "guidanceURL":"https://www.gov.uk/government/publications/sr2015-no18-metal-recycling-vehicle-storage-depollution-and-dismantling-facility",
   "locationRules":"",
   "permitBaselineReportRequired":"",
   "permitCost":"£1,630",
   "subsistenceFee":"£1,580",
   "permitFirePlanNeeded":"Yes",
   "permitID":"SR-2015-18",
   "permitName":"Metal recycling, vehicle storage, depollution and dismantling facility",
   "permitNatureHeritageSurvey":"Yes",
   "permitPreAppRequired":"Yes",
   "permitSpecialCase":"Yes",
   "permitTechnicalAbilityEvidence":"Yes",
   "permitWasteRecoveryPlan":"No",
   "permitWeight":"Less than 25,000 tonnes a year of waste metal and less than 5,000 tonnes a year of waste motor vehicles",
   "sitePlanNeeded":"Yes",
   "specialCase":"Yes",
   "specialCaseText":"",
   "technicalAbilityEvidence":"Yes",
   "WAMITAB":"WAMITAB Level 4 Medium Risk Operator Competence for Physical Treatment (601/8531/4) (MROC2)",
   "wasteRecoveryPlan":"No",
   "digitalMVP":"Yes",
   "permitRefNumber":"MT2653JF",
   "GOTEMAIL":"YES",
   "SaveReturn":"YES",
   "saveReturnEmail" : "info@test.com",
   "saveReturnEmailResent" : "info@test.com",
   "costTime":"yes",
   "drainage":"Sewer",
   "specialCasePageVisited":"Yes",
   "readRules":"yes",
   "preAppDiscussion":"yes",
   "preAppDiscussionRefName":"Fred Smith, Birmingham",
   "isContactAnAgent":[
      "yes"
   ],
   "contactFirstName":"Regina",
   "contactLastName":"Burnett",
   "agentCompany":"Deacon Mccall Ltd",
   "contactTelephone":"01179123456",
   "contactEmail":"cucaty@example.com",
   "operatorType":"Limited company",
   "companyRegNum":"04094290",
   "companyNumber":"04094290",
   "companyName":"Southern Star Power Plc",
   "companyAddress":"123 Sleeve Road, London AB1 6BU",
   "director":[
      "John Smith",
      "David Neil Cowhill",
      "David Docker",
      "Paul John Vermeer",
      "John Richard Kennedy",
      "Bob McTaggart",
      "Rachel McTall",
      "Colin Simon Paul",
      "David Rodderton",
      "Gary Martin Stokenham"
   ],
   "directorDobDay":{
     "John Smith":"12",
     "David Neil Cowhill":"12",
     "David Docker":"12",
     "Paul John Vermeer":"12",
     "John Richard Kennedy":"12",
     "Bob McTaggart":"12",
     "Rachel McTall":"12",
     "Colin Simon Paul":"12",
     "David Rodderton":"12",
     "Gary Martin Stokenham":"12"
   },
   "directorDobRest":{
      "John Smith":"/4/1963",
      "David Neil Cowhill":"/2/1965",
      "David Docker":"/5/1963",
      "Paul John Vermeer":"/8/1963",
      "John Richard Kennedy":"/9/1964",
      "Bob McTaggart":"/11/1971",
      "Rachel McTall":"/6/1972",
      "Colin Simon Paul":"/11/1960",
      "David Rodderton":"/6/1963",
      "Gary Martin Stokenham":"/11/1952"
   },
   "offences":"yes",
   "offencesDetailsName":"Dylan Carr",
   "offencesDetailsPosition":"Bryant and Cannon Co",
   "offencesPenalty":"Proident adipisicing aliqua Natus doloribus asperiores excepteur assumenda amet non",
   "offencesDetailsDobDay":"4",
   "offencesDetailsDobMonth":"11",
   "offencesDetailsDobYear":"2002",
   "bankruptcyInsolvency":"yes",
   "bankruptcyInsolvencyDetails":"Went bankrupt in June 2007",
   "siteName":"Car Breakers Yard",
   "siteGridRef":"ST 58132 72695",
   "sitePostCode":"BS1 5AH",
   "siteAddress":"5 GRANGE ROAD BRISTOL",
   "sitePlanFilename":"success-one.pdf",
   "industryScheme":"WAMITAB-CIWM",
   "industrySchemeDetails":"",
   "technicalCertificateFile":"success-two.pdf",
   "manSys":"EC Eco management and audit scheme (EMAS)",
   "firePlanFilename":"success-three.pdf",
   "confidential":"yes",
   "confidentialReasons":"The way I handle car parts storage is a trade secret",
   "invoicePostCode":"BS1 5TH",
   "invoiceAddress":"9a GRANGE ROAD BRISTOL",
   "invoiceName":"Finance Team",
   "invoiceEmail":"finance@mycompany.co.uk",
   "invoiceTelephone":"01179865432"
}
